import crypto from 'node:crypto';
import express from 'express';
import helmet from 'helmet';
import {rateLimit} from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import pg from 'pg';
import {z} from 'zod';
import {digest,maskContact,randomToken,verificationCode} from './security.js';

const {Pool}=pg;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:true}:false});
const app=express(),uuid=()=>crypto.randomUUID();
app.disable('x-powered-by');
app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:'256kb'}));
app.use('/api/',rateLimit({windowMs:60_000,limit:120,standardHeaders:'draft-7',legacyHeaders:false}));
app.use('/api/auth/',rateLimit({windowMs:15*60_000,limit:20,standardHeaders:'draft-7',legacyHeaders:false}));

const roles=['Safari traveller','Photographer','Filmmaker','Guide','Researcher','Conservation practitioner','Safari enthusiast'];
const registration=z.object({givenName:z.string().trim().min(1).max(60),familyName:z.string().trim().min(1).max(60),displayName:z.string().trim().min(1).max(60),handle:z.string().regex(/^[A-Za-z0-9_]{3,30}$/),birthDate:z.coerce.date(),homeCountry:z.string().trim().min(1).max(60),role:z.enum(roles),bio:z.string().trim().max(240).default(''),verificationMethod:z.enum(['email','mobile']),email:z.string().email().optional().or(z.literal('')),mobile:z.string().regex(/^\+?[0-9 ()-]{7,24}$/).optional().or(z.literal('')),password:z.string().min(12).max(128),acceptedTerms:z.literal(true),acceptedPrivacy:z.literal(true),acceptedGuidelines:z.literal(true)}).superRefine((v,ctx)=>{if(v.verificationMethod==='email'&&!v.email)ctx.addIssue({code:'custom',message:'Email is required.'});if(v.verificationMethod==='mobile'&&!v.mobile)ctx.addIssue({code:'custom',message:'Mobile number is required.'})});
const publicMember=row=>({id:row.id,displayName:row.display_name,handle:row.handle,role:row.role,homeCountry:row.home_country,bio:row.bio,verified:Boolean(row.verified_at),createdAt:row.created_at});
const fail=(res,status,message)=>res.status(status).json({message});
const parseCookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2));
async function requireMember(req,res,next){try{const token=parseCookies(req).circle_session;if(!token)return fail(res,401,'Sign in to continue.');const {rows}=await pool.query('SELECT m.* FROM sessions s JOIN members m ON m.id=s.member_id WHERE s.token_hash=$1 AND s.expires_at>now() AND m.status=$2',[digest(token),'active']);if(!rows[0])return fail(res,401,'Your session has expired.');req.member=rows[0];next()}catch(error){next(error)}}
async function deliverVerification(member,code){const url=process.env.VERIFICATION_PROVIDER_URL,token=process.env.VERIFICATION_PROVIDER_TOKEN;if(!url||!token)throw new Error('Verification delivery is not configured.');const destination=member.email||member.mobile,response=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({destination,channel:member.email?'email':'sms',template:'circle-verification',variables:{code,expiresMinutes:10}})});if(!response.ok)throw new Error('Verification delivery failed.');}
async function issueSession(res,memberId){const token=randomToken();await pool.query('INSERT INTO sessions(token_hash,member_id,expires_at) VALUES($1,$2,now()+interval \'30 days\')',[digest(token),memberId]);res.cookie('circle_session',token,{httpOnly:true,secure:process.env.SESSION_COOKIE_SECURE!=='false',sameSite:'strict',path:'/',maxAge:30*86400_000});}
async function transaction(work){const client=await pool.connect();try{await client.query('BEGIN');const result=await work(client);await client.query('COMMIT');return result}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}

app.post('/api/auth/register',async(req,res,next)=>{const parsed=registration.safeParse(req.body);if(!parsed.success)return fail(res,400,parsed.error.issues[0].message);const v=parsed.data,contact=v.verificationMethod==='email'?v.email.toLowerCase():v.mobile.replace(/[^+\d]/g,''),memberId=uuid(),verificationId=uuid(),code=verificationCode();try{const passwordHash=await bcrypt.hash(v.password,12);await transaction(async client=>{const {rows}=await client.query(`INSERT INTO members(id,given_name,family_name,display_name,handle,birth_date,home_country,role,bio,email,mobile,password_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[memberId,v.givenName,v.familyName,v.displayName,v.handle,v.birthDate,v.homeCountry,v.role,v.bio,v.verificationMethod==='email'?contact:null,v.verificationMethod==='mobile'?contact:null,passwordHash]);await client.query('INSERT INTO verifications(id,member_id,code_hash,expires_at) VALUES($1,$2,$3,now()+interval \'10 minutes\')',[verificationId,memberId,digest(code)]);await deliverVerification(rows[0],code)});res.status(201).json({registrationId:verificationId,maskedDestination:maskContact(contact)})}catch(error){if(error.code==='23505')return fail(res,409,'That handle or contact is already registered.');next(error)}});
app.post('/api/auth/verify',async(req,res,next)=>{const parsed=z.object({registrationId:z.string().uuid(),code:z.string().regex(/^\d{6}$/)}).safeParse(req.body);if(!parsed.success)return fail(res,400,'Enter the six-digit verification code.');try{const {rows}=await pool.query(`UPDATE verifications SET attempts=attempts+1,consumed_at=CASE WHEN code_hash=$2 THEN now() ELSE consumed_at END WHERE id=$1 AND consumed_at IS NULL AND expires_at>now() AND attempts<5 RETURNING member_id,(code_hash=$2) valid`,[parsed.data.registrationId,digest(parsed.data.code)]);if(!rows[0]?.valid)return fail(res,400,'The code is invalid or has expired.');const result=await pool.query('UPDATE members SET verified_at=now() WHERE id=$1 RETURNING *',[rows[0].member_id]);await pool.query('INSERT INTO member_settings(member_id) VALUES($1) ON CONFLICT DO NOTHING',[rows[0].member_id]);await issueSession(res,rows[0].member_id);res.json({verified:true,member:publicMember(result.rows[0])})}catch(error){next(error)}});
app.post('/api/auth/resend',async(req,res,next)=>{const parsed=z.object({registrationId:z.string().uuid()}).safeParse(req.body);if(!parsed.success)return fail(res,400,'Start account creation again.');try{const {rows}=await pool.query('SELECT v.id,m.* FROM verifications v JOIN members m ON m.id=v.member_id WHERE v.id=$1 AND v.consumed_at IS NULL AND m.verified_at IS NULL',[parsed.data.registrationId]);if(!rows[0])return fail(res,404,'That verification request is no longer available.');const code=verificationCode();await pool.query(`UPDATE verifications SET code_hash=$1,expires_at=now()+interval '10 minutes',attempts=0 WHERE id=$2`,[digest(code),parsed.data.registrationId]);await deliverVerification(rows[0],code);res.json({sent:true,maskedDestination:maskContact(rows[0].email||rows[0].mobile)})}catch(error){next(error)}});
app.post('/api/auth/recover',async(req,res,next)=>{const parsed=z.object({identifier:z.string().trim().min(1).max(254)}).safeParse(req.body);if(!parsed.success)return fail(res,400,'Enter your verified contact or handle.');try{const {rows}=await pool.query(`SELECT * FROM members WHERE lower(handle::text)=lower($1) OR lower(coalesce(email::text,''))=lower($1) OR mobile=$1 LIMIT 1`,[parsed.data.identifier]);if(rows[0]){const code=verificationCode(),id=uuid();await pool.query(`INSERT INTO verifications(id,member_id,code_hash,expires_at) VALUES($1,$2,$3,now()+interval '10 minutes')`,[id,rows[0].id,digest(code)]);await deliverVerification(rows[0],code)}res.json({accepted:true})}catch(error){next(error)}});
app.post('/api/auth/login',async(req,res,next)=>{const parsed=z.object({identifier:z.string().trim().min(1).max(254),password:z.string().min(1).max(128)}).safeParse(req.body);if(!parsed.success)return fail(res,400,'Enter your account details.');try{const {rows}=await pool.query('SELECT * FROM members WHERE lower(handle::text)=lower($1) OR lower(coalesce(email::text,\'\'))=lower($1) OR mobile=$1 LIMIT 1',[parsed.data.identifier]);const member=rows[0],valid=member&&await bcrypt.compare(parsed.data.password,member.password_hash);if(!valid||!member.verified_at||member.status!=='active')return fail(res,401,'The account details could not be verified.');await issueSession(res,member.id);res.json({member:publicMember(member)})}catch(error){next(error)}});

app.get('/api/circle/members',requireMember,async(req,res,next)=>{try{const query=String(req.query.query||'').slice(0,80),role=String(req.query.role||'').slice(0,60),{rows}=await pool.query(`SELECT m.* FROM members m WHERE m.status='active' AND m.verified_at IS NOT NULL AND m.id<>$1 AND NOT EXISTS(SELECT 1 FROM blocks b WHERE (b.blocker_id=$1 AND b.blocked_id=m.id) OR (b.blocker_id=m.id AND b.blocked_id=$1)) AND ($2='' OR m.display_name ILIKE '%'||$2||'%' OR m.handle::text ILIKE '%'||$2||'%' OR m.home_country ILIKE '%'||$2||'%') AND ($3='' OR m.role=$3) ORDER BY m.created_at DESC LIMIT 50`,[req.member.id,query,role]);res.json({members:rows.map(publicMember)})}catch(error){next(error)}});
app.put('/api/circle/me',requireMember,async(req,res,next)=>{const parsed=z.object({name:z.string().trim().min(1).max(60),handle:z.string().regex(/^[A-Za-z0-9_]{3,30}$/),role:z.enum(roles),home:z.string().trim().max(60),bio:z.string().trim().max(240)}).safeParse(req.body);if(!parsed.success)return fail(res,400,parsed.error.issues[0].message);try{const v=parsed.data,{rows}=await pool.query('UPDATE members SET display_name=$1,handle=$2,role=$3,home_country=$4,bio=$5,updated_at=now() WHERE id=$6 RETURNING *',[v.name,v.handle,v.role,v.home,v.bio,req.member.id]);res.json({member:publicMember(rows[0])})}catch(error){if(error.code==='23505')return fail(res,409,'That handle is already in use.');next(error)}});
app.put('/api/circle/me/settings',requireMember,async(req,res,next)=>{const parsed=z.object({profileVisibility:z.enum(['public','members','followers']),messagePrivacy:z.enum(['members','followers','none']),protectLocations:z.boolean(),notifications:z.boolean()}).safeParse(req.body);if(!parsed.success)return fail(res,400,'Invalid Circle preferences.');const v=parsed.data;try{await pool.query(`INSERT INTO member_settings(member_id,profile_visibility,message_privacy,protect_locations,notifications) VALUES($1,$2,$3,$4,$5) ON CONFLICT(member_id) DO UPDATE SET profile_visibility=$2,message_privacy=$3,protect_locations=$4,notifications=$5`,[req.member.id,v.profileVisibility,v.messagePrivacy,v.protectLocations,v.notifications]);res.json({settings:v})}catch(error){next(error)}});
app.post('/api/circle/posts',requireMember,async(req,res,next)=>{const parsed=z.object({type:z.enum(['sighting','photograph','story','question','film']),species:z.string().trim().max(90).default(''),country:z.string().trim().max(60).default(''),place:z.string().trim().max(100).default(''),locationProtected:z.boolean().default(true),text:z.string().trim().min(1).max(1800),visibility:z.enum(['public','followers','private']),image:z.string().max(200_000).default('')}).safeParse(req.body);if(!parsed.success)return fail(res,400,parsed.error.issues[0].message);if(parsed.data.image)return fail(res,422,'Photographs must be uploaded through the media service.');try{const v=parsed.data,id=uuid(),{rows}=await pool.query(`INSERT INTO posts(id,member_id,type,species,country,place,location_protected,body,visibility) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[id,req.member.id,v.type,v.species,v.country,v.locationProtected?'':v.place,v.locationProtected,v.text,v.visibility]);const p=rows[0];res.status(201).json({post:{id:p.id,author:req.member.display_name,role:req.member.role,type:p.type,species:p.species,country:p.country,place:p.place,locationProtected:p.location_protected,text:p.body,visibility:p.visibility,image:'',liked:false,comments:[],createdAt:p.created_at}})}catch(error){next(error)}});
app.delete('/api/circle/posts/:id',requireMember,async(req,res,next)=>{try{const {rowCount}=await pool.query('UPDATE posts SET deleted_at=now() WHERE id=$1 AND member_id=$2 AND deleted_at IS NULL',[req.params.id,req.member.id]);if(!rowCount)return fail(res,404,'Post not found.');res.json({deleted:true})}catch(error){next(error)}});
app.post('/api/circle/posts/:id/appreciation',requireMember,async(req,res,next)=>{const liked=req.body?.liked===true;try{if(liked)await pool.query('INSERT INTO appreciations(member_id,post_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.member.id,req.params.id]);else await pool.query('DELETE FROM appreciations WHERE member_id=$1 AND post_id=$2',[req.member.id,req.params.id]);res.json({liked})}catch(error){next(error)}});
app.post('/api/circle/posts/:id/comments',requireMember,async(req,res,next)=>{const parsed=z.object({text:z.string().trim().min(1).max(300)}).safeParse(req.body);if(!parsed.success)return fail(res,400,'Write a comment before posting.');try{const id=uuid(),{rows}=await pool.query('INSERT INTO comments(id,post_id,member_id,body) VALUES($1,$2,$3,$4) RETURNING *',[id,req.params.id,req.member.id,parsed.data.text]);res.status(201).json({comment:{id,author:req.member.display_name,text:rows[0].body,createdAt:rows[0].created_at}})}catch(error){next(error)}});
app.post('/api/circle/members/:id/follow',requireMember,async(req,res,next)=>{try{await pool.query('INSERT INTO follows(follower_id,followed_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.member.id,req.params.id]);res.status(201).json({following:true})}catch(error){next(error)}});
app.delete('/api/circle/members/:id/follow',requireMember,async(req,res,next)=>{try{await pool.query('DELETE FROM follows WHERE follower_id=$1 AND followed_id=$2',[req.member.id,req.params.id]);res.json({following:false})}catch(error){next(error)}});
app.post('/api/circle/threads/:id/messages',requireMember,async(req,res,next)=>{const parsed=z.object({text:z.string().trim().min(1).max(1200),recipientId:z.string().uuid()}).safeParse(req.body);if(!parsed.success)return fail(res,400,'The message could not be sent.');try{const threadId=z.string().uuid().safeParse(req.params.id).success?req.params.id:uuid(),id=uuid(),message=await transaction(async client=>{await client.query('INSERT INTO threads(id) VALUES($1) ON CONFLICT DO NOTHING',[threadId]);await client.query('INSERT INTO thread_members(thread_id,member_id) VALUES($1,$2),($1,$3) ON CONFLICT DO NOTHING',[threadId,req.member.id,parsed.data.recipientId]);const {rows}=await client.query('INSERT INTO messages(id,thread_id,sender_id,body) VALUES($1,$2,$3,$4) RETURNING *',[id,threadId,req.member.id,parsed.data.text]);return rows[0]});res.status(201).json({message:{id,text:message.body,createdAt:message.created_at}})}catch(error){next(error)}});
app.post('/api/circle/members/:id/block',requireMember,async(req,res,next)=>{if(req.params.id===req.member.id)return fail(res,400,'You cannot block your own account.');try{await pool.query('INSERT INTO blocks(blocker_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.member.id,req.params.id]);res.status(201).json({blocked:true})}catch(error){next(error)}});
app.delete('/api/circle/blocks',requireMember,async(req,res,next)=>{try{await pool.query('DELETE FROM blocks WHERE blocker_id=$1',[req.member.id]);res.json({cleared:true})}catch(error){next(error)}});
app.post('/api/circle/reports',requireMember,async(req,res,next)=>{const parsed=z.object({targetType:z.enum(['member','post','message']),targetId:z.string().min(1).max(100),reason:z.string().min(3).max(120),details:z.string().max(800).default('')}).safeParse(req.body);if(!parsed.success)return fail(res,400,'Give a valid report reason.');try{const id=uuid();await pool.query('INSERT INTO reports(id,reporter_id,target_type,target_id,reason,details) VALUES($1,$2,$3,$4,$5,$6)',[id,req.member.id,parsed.data.targetType,parsed.data.targetId,parsed.data.reason,parsed.data.details]);res.status(201).json({report:{id,status:'open'}})}catch(error){next(error)}});

app.get('/healthz',async(_req,res)=>{try{await pool.query('SELECT 1');res.json({status:'ok'})}catch{res.status(503).json({status:'unavailable'})}});
app.use((error,_req,res,_next)=>{console.error(error);res.status(500).json({message:'The service could not complete that request.'})});
if(process.env.NODE_ENV!=='test')app.listen(Number(process.env.PORT||8080));
export {app,pool};
